LeaseCrunch.Web/Controllers/AspNetUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Text;
using System.Net;
using System.Web;
using System.Net.Mail;
using System.Web.Mvc;
using LeaseCrunch.Entities;
using LeaseCrunch.Service;
using Repository.Pattern.UnitOfWork;
using System.Web.Services;
using System.Web.Script.Services;
using Repository.Pattern.Infrastructure;
using Microsoft.AspNet.Identity;
using LeaseCrunch.Web.Models;
using System.Security.Claims;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Reflection;
using Microsoft.AspNet.Identity.EntityFramework;

namespace LeaseCrunch.Web.Controllers
{
    public class AspNetUsersController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        //public async Task<ActionResult> List()
        public ActionResult Index()
        {
            var roleStore = new RoleStore<IdentityRole>(db);
            var roleMngr = new RoleManager<IdentityRole>(roleStore);
            var roles = roleMngr.Roles.ToList();
            ViewBag.roles = new SelectList(roles, "Id", "Name");
            return View();
        }

        [HttpGet]
        //[WebMethod]
        //[ScriptMethod(ResponseFormat = ResponseFormat.Json)]
        public ActionResult List(bool disable, string filter)
        {
            LeaseCrunchContext data = new LeaseCrunchContext();

            //var query = from user in db.Users select user;
            var query = from vw_AspNetUsers in data.VAspNetUsers select vw_AspNetUsers;

            List<VAspNetUser> users = new List<VAspNetUser>();
            if (disable == false)
                query = query.Where(x => x.EmailConfirmed != disable);

            if (!string.IsNullOrEmpty(filter))
                query = query.Where(x => x.UserName.Contains(filter) || x.Email.Contains(filter) || x.FirstName.Contains(filter) || x.LastName.Contains(filter));

            var collection = query.Select(x => new
            {
                id = x.Id,
                name = x.FirstName + " " + x.LastName,
                firstname = x.FirstName,
                lastname = x.LastName,
                email = x.Email,
                role = x.Role
            });

            return Json(new { draw = 1, recordsTotal = collection.Count(), recordsFiltered = 50, data = collection }, JsonRequestBehavior.AllowGet);

        }


        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [WebMethod]
        [ScriptMethod(ResponseFormat = ResponseFormat.Json)]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            var applicationUser = db.Users.Find(id);
            db.Users.Remove(applicationUser);
            Message message = new Message
            {
                Status = true
            };
            db.SaveChanges();
            return Json(message);

        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Save")]
        [WebMethod]
        [ScriptMethod(ResponseFormat = ResponseFormat.Json)]
        //[ValidateAntiForgeryToken]
        //[HandleError(View = "AntiForgeryExceptionView", ExceptionType = typeof(HttpAntiForgeryException))]
        public async Task<ActionResult> Save(Guid id)
        {

            Message message = new Message
            {
                Status = true
            };
            string e_mail = Request.Form["email"];
            var user = await UserManager.FindByNameAsync(e_mail);
            if (user == null)
            {
                ApplicationUser applicationUser = new ApplicationUser();
                applicationUser.FirstName = Request.Form["firstname"];
                applicationUser.LastName = Request.Form["lastname"];
                applicationUser.UserName = applicationUser.Email = Request.Form["email"];
                applicationUser.EmailConfirmed = true;
                applicationUser.UserLevel = 0;
                applicationUser.ParentId = null;

                var result = await UserManager.CreateAsync(applicationUser, "P@ssw0rd");
                if (result.Succeeded)
                {
                    user = await UserManager.FindByNameAsync(e_mail);
                    string role = Request.Form["roles"].Trim().Replace('\n', ' ');
                    var roleresult = UserManager.AddToRole(user.Id, role);
                    var code = await UserManager.GeneratePasswordResetTokenAsync(user.Id);
                    var callbackUrl = Url.Action("Register", "Account", new { UserId = user.Id, code = code }, protocol: Request.Url.Scheme);

                    StringBuilder email = new StringBuilder();
                    email.AppendLine("Hi " + Request.Form["firstname"] + " " + Request.Form["lastname"] + ",");
                    email.AppendLine("<br><br>");
                    email.AppendLine("You are invited to create a Admin Account on LeaseCrunch&#46;com.");
                    email.AppendLine("<br><br>");
                    email.AppendLine("Click on the link below to get started.");
                    email.AppendLine("<br><br>");
                    email.AppendLine("Create your account by clicking here:<a href=\"" + callbackUrl + "\">link</a> ");
                    email.AppendLine("<br><br>");
                    email.AppendLine("Thanks,");
                    email.AppendLine("<br><br>");
                    email.AppendLine("LeaseCrunch Support");

                    MailMessage mailMessage = new MailMessage();
                    mailMessage.To.Add(new MailAddress(Request.Form["email"]));  // replace with valid value 
                    mailMessage.From = new MailAddress("support@lcsupport.com");  // replace with valid value
                    mailMessage.Subject = "LC Crunch Support";
                    mailMessage.Body = email.ToString();
                    mailMessage.IsBodyHtml = true;

                    using (var smtp = new SmtpClient())
                    {
                        await smtp.SendMailAsync(mailMessage);
                    }
                }
            }
            else
            {
                message.Status = false;
            }
            if (id == Guid.Empty)
            {

            }
            else
            {
                ApplicationUser applicationUser = new ApplicationUser();
                applicationUser = db.Users.Find(id.ToString());
                applicationUser.FirstName = Request.Form["firstname"];
                applicationUser.LastName = Request.Form["lastname"];
                applicationUser.Email = Request.Form["email"];
                db.Entry(applicationUser).State = EntityState.Modified;
                await db.SaveChangesAsync();
                db.SaveChanges();
            }
            return Json(message);

        }




        //private readonly IAspNetUsersService _aspNetUsersService;
        //private readonly IUnitOfWorkAsync _unitOfWorkAsync;

        //public AspNetUsersController(IUnitOfWorkAsync unitOfWorkAsync,
        //    IAspNetUsersService aspNetUsersService)
        //{
        //    _unitOfWorkAsync = unitOfWorkAsync;
        //    _aspNetUsersService = aspNetUsersService;
        //}      // GET: AspNetUsers

        //public async Task<ActionResult> Index()
        //{
        //    //return View(await db.AspNetUsers.ToListAsync());
        //    return View();
        //}

        //// GET: AspNetUsers/Details/5
        //public async Task<ActionResult> Details(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    AspNetUsers aspNetUsers = await db.AspNetUsers.FindAsync(id);
        //    if (aspNetUsers == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(aspNetUsers);
        //}

        //// GET: AspNetUsers/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: AspNetUsers/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Create([Bind(Include = "Id,Address,City,State,PostalCode,Email,string1,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,ParentId,UserLevel,FirstName,LastName,Status")] AspNetUsers aspNetUsers)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.AspNetUsers.Add(aspNetUsers);
        //        await db.SaveChangesAsync();
        //        return RedirectToAction("Index");
        //    }

        //    return View(aspNetUsers);
        //}

        //// GET: AspNetUsers/Edit/5
        //public async Task<ActionResult> Edit(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    AspNetUsers aspNetUsers = await db.AspNetUsers.FindAsync(id);
        //    if (aspNetUsers == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(aspNetUsers);
        //}

        //// POST: AspNetUsers/Edit/5

LeaseCrunch.Web/Views/AspNetUsers/Delete.cshtml
@model LeaseCrunch.Entities.AspNetUsers

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AspNetUsers</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.string1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.string1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityStamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumberConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TwoFactorEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEndDateUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessFailedCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LeaseCrunch.Web/Views/AspNetUsers/Details.cshtml
@model LeaseCrunch.Entities.AspNetUsers

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>AspNetUsers</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.string1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.string1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasswordHash)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasswordHash)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SecurityStamp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SecurityStamp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumberConfirmed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumberConfirmed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TwoFactorEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TwoFactorEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEndDateUtc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LockoutEnabled)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LockoutEnabled)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AccessFailedCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccessFailedCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ParentId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ParentId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserLevel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserLevel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LeaseCrunch.Web/Views/AspNetUsers/Index.cshtml
 <!-- Content -->
<div class="content">
    <div class="col-sm-12">
        <div class="row">
            <div class="col-xs-12 bg-white shadow">
                <div class="title">LeaseCrunch Admin</div>
            </div>
        </div>
        <div class="row row-filter-actions">
            <div class="col-sm-offset-1 col-sm-10">
                <div class="col-md-5 col-sm-12 no-left-padd-xs no-right-padd-xs no-left-padd-sm no-right-padd-sm no-left-padd-md no-left-padd-lg">
                    <div class="container-disalbed-accounts">
                        <div class="form">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" id="disabledaccount"> Include disabled accounts
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-7 col-sm-12 no-left-padd-xs no-right-padd-xs no-left-padd-sm no-right-padd-sm no-right-padd-md no-right-padd-lg">
                    <div class="container-filter">
                        <div class="form">
                            <div class="form-group">
                                <input type="text" class="form-control" id="filter">
                                <button class="btn btn-primary btn-filter" id="showfilter"><i class="fa fa-filter"></i> Filter</button>
                                <button class="btn btn-primary btn-invite" id="showinvite"><i class="fa fa-envelope-o"></i> Invite</button>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-offset-1 col-sm-10">
                <table class="table table-bordered table-listing js-data-table" id="UserList">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Email Address</th>
                            <th>Role</th>
                            <th class="actions text-center">Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<!-- /Content -->
<!-- Modal Company Listing -->

<div class="modal fade" id="UserModal" tabindex="-1" role="dialog" aria-labelledby="CompanyListingLabel">
    @using (Html.BeginForm(null, null, FormMethod.Get, new { id = "frm" }))
    {
        @*<form class="cmxform" id="frm" method="get" action="">*@
        @*@Html.AntiForgeryToken()*@
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="modalheading">Add / Edit User</h4>
                </div>
                <div class="modal-body">
                    <div class="form-horizontal">
                        @*@Html.Hidden("userid")*@
                        <input id="userid" name="userid" type="hidden" />
                        <div class="form-group required">
                            <label for="" class="col-sm-4 control-label">First Name</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" id="firstname" required>
                                <div class="required-staric">*</div>
                            </div>
                        </div>
                        <div class="form-group required">
                            <label for="" class="col-sm-4 control-label">Last Name</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" id="lastname" required>
                                <div class="required-staric">*</div>
                            </div>
                        </div>
                        <div class="form-group required">
                            <label for="" class="col-sm-4 control-label">Email Address</label>
                            <div class="col-sm-7">
                                <input type="text" class="form-control" id="email" required>
                                <div class="required-staric">*</div>
                            </div>
                        </div>
                        <div class="form-group required">
                            <label for="" class="col-sm-4 control-label">Role</label>
                            <div class="col-sm-7">
                                @Html.DropDownList("roles", null, htmlAttributes: new { @class = "form-control", required = string.Empty })
                                <div class="required-staric">*</div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-4 col-sm-2">
                                <button class="btn btn-block btn-primary" id="save">SAVE</button>

                            </div>
                            <div class="col-sm-2">
                                <button class="btn btn-block btn-secondary" data-dismiss="modal">CANCEL</button>
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
        @*</form>*@
    }
</div>
<!-- /Modal Company Listing -->


<script type="text/javascript">
    $(document).ready(function () {
        var baseUrl = "@Url.Action("List", "AspNetUsers")";
        var url = getURL(baseUrl);

        var table = $('#UserList').DataTable({
            bPaginate: false,
            serverSide: false,
            searching: false,
            destroy: true,
            processing: true,
            ajax:
                {
                    "url": url
                },
            columns: [
        { "data": "name", "orderable": true },
        { "data": "email", "orderable": true },
        { "data": "role", "orderable": true }
            ],
            columnDefs: [{
                "targets": 3,
                "data": null,
                "defaultContent": '<i class="fa fa-pencil icon-edit"></i><i class="fa fa-ban icon-delete"></i>'
            }]
        });
        //Include disabled accounts
        $('body').on('click', '#showfilter', function () {
            status = $('#disabledaccount').is(':checked');
            filter = $('#filter').val();
            table.ajax.url(getURL(baseUrl)).load();

            if (filter.trim() == '') {
                message = 'No search criteria to perform';
            } else {
                message = 'Record has been filtered';
            }
            toastr.success(message, 'SUCCESS', { timeOut: 5000, closeButton: true });

        });

        //Include disabled accounts
        $('body').on('click', '#disabledaccount', function () {
            status = $('#disabledaccount').is(':checked');
            filter = $('#filter').val();
            table.ajax.url(getURL(baseUrl)).load();
            if (status == 'true') {
                message = 'Disabled users included in grid';
            } else {
                message = 'Disabled users excluded from grid';
            }
            toastr.success(message, 'SUCCESS', { timeOut: 5000, closeButton: true });
        });

        // table.ajax.reload();
        //invite new LC admin
        $('body').on('click', '#showinvite', function () {
            $("#modalheading").text("Invite LC Admin");
            //$('input[name="userid"]').attr('value', "-1");
            $("#userid").val('00000000-0000-0000-0000-000000000000');
            $("#firstname").val('');
            $("#lastname").val('');
            $("#email").val('');
            $("#UserModal").modal('show');
        });

        $('#UserList tbody').on('click', 'i', function () {

            var type = $(this).attr("class");
            var data = table.row($(this).parents('tr')).data();

            if (type == 'fa fa-pencil icon-edit') {
                $("#modalheading").text("Add / Edit User");
                $("#userid").val(data.id);
                $("#firstname").val(data.firstname);
                $("#lastname").val(data.lastname);
                $("#email").val(data.email);
                $("#roles option").each(function () { this.selected = $(this).text() == data.roles; });
                $("#UserModal").modal('show');
            }
            else if (type == 'fa fa-ban icon-delete') {
                $(this).confirmation({
                    onConfirm: function () {
                        $.ajax({
                            url: '@Url.Action("Delete", "AspNetUsers")',
                            type: 'POST',
                            data: {
                                id: data.id
                            },
                            success: function (response) {
                                table.ajax.url(getURL(baseUrl)).load();
                            },
                            error: function (msg) {
                                alert('Exception \n' + response.status);
                            }
                        });
                    }
                });
            }
        });

        @*$('#frm').validator().on('submit', function (e) {
            if (e.isDefaultPrevented()) {
            } else {
                $.ajax({
                    url: '@Url.Action("Save", "AspNetUsers")',
                     type: 'POST',
                    data: {
                        id: $('#userid').val(),
                        firstname: $('#firstname').val(),
                        lastname: $('#lastname').val(),
                        email: $('#email').val(),
                        roles: $('#roles').text()
                    },
                    success: function () {
                        status = $('#disabledaccount').is(':checked');
                        filter = $('#filter').val();
                        table.ajax.url(getURL(baseUrl)).load();


                        alert($("#userid").val());
                       if ($("#userid").val('00000000-0000-0000-0000-000000000000')){
                           message = 'Record has been inserted';
                        }else{
                           message = 'Record has been updated';
                        }
                       toastr.success(message, 'SUCCESS', { timeOut: 5000, closeButton: true });

                       $("#UserModal").modal('hide');


                    },
                    error: function (msg) {
                        alert('Exception \n' + response.status);
                    }


                });
            }
        });
*@
    });

    var checkTab = function () {
        var $tab = $('#myTab'), $active = $tab.find('.active'), text = $active.find('a').text();
        return text;
    };

    var deleteCompany = function (a) {
        alert(a);
    }

    var loadGrid = function () {

    }

    var getURL = function (baseUrl) {
        var url = baseUrl + "?disable=" + $('#disabledaccount').is(':checked') + "&filter=" + $("#filter").val();
        //alert(url);
        return url;
    }

</script>

@section scripts{
    @Scripts.Render("~/bundles/datatable")
}