LeaseCrunch.Web/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LeaseCrunch.Entities;
using LeaseCrunch.Service;
using LeaseCrunch.Common;
using Repository.Pattern.UnitOfWork;
using System.Web.Services;
using System.Web.Script.Services;
using System.Text;
using Repository.Pattern.Infrastructure;
using LeaseCrunch.Web.Models;
using System.Data.Entity.Validation;
using System.Net.Mail;
using Microsoft.AspNet.Identity;
using System.Security.Claims;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Reflection;
using Microsoft.AspNet.Identity.EntityFramework;
using Newtonsoft.Json;
using System.Linq.Expressions;
using System.Collections;

namespace LeaseCrunch.Web.Controllers
{
    //[Authorize]
    public class CompaniesController : Controller
    {
        LeaseCrunchContext db = new LeaseCrunchContext();
        // ApplicationDbContext adb = new ApplicationDbContext();

        private readonly IAccountTypeService _accountTypeService;
        private readonly ICompanyAccountsConfigurationService _companyAccountsConfigurationService;
        private readonly ICompanyAccountService _companyAccountService;
        private readonly IVCompanyAccountService _vcompanyAccountService;
        private readonly ICustomizationAssetTypeService _customizationAssetTypeService;
        private readonly ICustomizationCustomFieldService _customizationCustomFieldService;
        private readonly ICustomizationCostCenterService _customizationCostCenterService;
        private readonly ICustomerService _customerService;
        private readonly ICompanyService _companyService;
        private readonly ILocationService _locationService;
        private readonly ICountryService _countryService;
        private readonly IAccountingStandardService _accountingStandardService;
        private readonly IStateService _stateService;
        private readonly IUnitOfWorkAsync _unitOfWorkAsync;

        public CompaniesController(IUnitOfWorkAsync unitOfWorkAsync,
            ICompanyService companyService, ICountryService countryService, IAccountingStandardService accountingStandardService, IStateService stateService, ILocationService locationService, ICustomerService customerService, ICustomizationAssetTypeService customizationAssetTypeService, ICustomizationCustomFieldService customizationCustomFieldService, ICustomizationCostCenterService customizationCostCenterService, IAccountTypeService accountTypeService, IVCompanyAccountService vcompanyAccountService, ICompanyAccountsConfigurationService companyAccountsConfigurationService, ICompanyAccountService companyAccountService)
        {
            _accountTypeService = accountTypeService;
            _customizationAssetTypeService = customizationAssetTypeService;
            _customizationCustomFieldService = customizationCustomFieldService;
            _customizationCostCenterService = customizationCostCenterService;
            _unitOfWorkAsync = unitOfWorkAsync;
            _companyService = companyService;
            _countryService = countryService;
            _accountingStandardService = accountingStandardService;
            _stateService = stateService;
            _locationService = locationService;
            _customerService = customerService;
            _vcompanyAccountService = vcompanyAccountService;
            _companyAccountsConfigurationService = companyAccountsConfigurationService;
            _companyAccountService = companyAccountService;
        }

        // GET: Companies
        public async Task<ActionResult> Index(int id = 0)
        {
            ApplicationUser user = new ApplicationUser();
            UserManager<ApplicationUser> UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new ApplicationDbContext()));
            user = UserManager.FindById(User.Identity.GetUserId());
            ViewBag.UserLevel = user.UserLevel;

            if (id > 0)
            {
                Session["customerid"] = id;
            }
            else if (id == 0 && Session["customerid"] != null)
            {
                id = Convert.ToInt32(Session["customerid"].ToString());
            }
            else if (id == 0 && Session["customerid"] == null)
            {
                if (user != null)
                {
                    //id = user.CustomerId.Value;// (user.CustomerId == null) ? user.CustomerId.Value : 0;
                    Session["customerid"] = id = user.CustomerId.Value;
                }
            }
            
            var customer = _customerService.Queryable().Where(x => x.Id == id).FirstOrDefault();
            if (customer != null) Session["customer"] = customer.Name;

            var comp = _vcompanyAccountService.Queryable().Where(x => x.CustomerId == id).FirstOrDefault();
            if (comp != null)
            {
                Session["company"] = comp.Companies;
            }


            ApplicationDbContext adb = new ApplicationDbContext();
            var roleStore = new RoleStore<IdentityRole>(adb);
            var roleMngr = new RoleManager<IdentityRole>(roleStore);
            string[] rolesid = { "2e4d9b8e-a27b-4ab7-9a53-c9ccc2b63a9b", "3e4d9b8e-a27b-4ab7-9a53-c9ccc2b63a9b", "5e4d9b8e-a27b-4ab7-9a53-c9ccc2b63a9b" };
            var roles = roleMngr.Roles.Where(r => rolesid.Contains(r.Id)).ToList();
            ViewBag.roles = new SelectList(roles, "Id", "Name");

            ViewBag.rolesJson = JsonConvert.SerializeObject(roles);
            ViewBag.accountingStandardServiceJson = JsonConvert.SerializeObject(_accountingStandardService.Queryable().ToList());

            ViewBag.customizationAssetTypeService = _customizationAssetTypeService.Queryable().Where(x => x.CustomerId == id);
            ViewBag.customizationCustomFields = _customizationCustomFieldService.Queryable().Where(x => x.CustomerId == id);
            ViewBag.CustomizationCostCenters = _customizationCostCenterService.Queryable().Where(x => x.CustomerId == id); ;

            ViewBag.countryidl = new SelectList(_countryService.Queryable().ToList(), "Id", "Name");
            ViewBag.countryidc = new SelectList(_countryService.Queryable().ToList(), "Id", "Name");
            ViewBag.stateidl = new SelectList(_stateService.Queryable().ToList(), "Id", "Name", "id");
            ViewBag.stateidc = new SelectList(_stateService.Queryable().ToList(), "Id", "Name", "id");
            ViewBag.AccountingStandardId = new SelectList(_accountingStandardService.Queryable().ToList(), "Id", "Name");

            //Populate GL Account
            ViewBag.Leases_Operating_Leases = new SelectList(_accountTypeService.Queryable().Where(x => x.ParentId == (int)Common.Leases.Leases_Operating_Leases).ToList(), "Id", "Name", "--Select Operating Leases--");
            ViewBag.Leases_Finance_Leases = new SelectList(_accountTypeService.Queryable().Where(x => x.ParentId == (int)Common.Leases.Leases_Finance_Leases).ToList(), "Id", "Name");
            ViewBag.Non_Leases_Operating_Leases = new SelectList(_accountTypeService.Queryable().Where(x => x.ParentId == (int)Common.Leases.Non_Leases_Operating_Leases).ToList(), "Id", "Name");
            ViewBag.Non_Leases_Finance_Leases = new SelectList(_accountTypeService.Queryable().Where(x => x.ParentId == (int)Common.Leases.Non_Leases_Finance_Leases).ToList(), "Id", "Name");
            ViewBag.Classification = new SelectList(_accountTypeService.Queryable().Where(x => x.ParentId == (int)Common.Leases.Classification).ToList(), "Id", "Name");
            ViewBag.FinancialStatement = new SelectList(_accountTypeService.Queryable().Where(x => x.ParentId == (int)Common.Leases.FinancialStatement).ToList(), "Id", "Name");

            PopulateCompany();

            return View();
        }

        [HttpGet]
        public JsonResult PopulateCompany()
        {
            int customerid = Convert.ToInt32(Session["customerid"]);
            var company = _companyService.Queryable().Where(c => c.CustomerId == customerid).ToList();
            var collection = company.Select(x => new
            {
                id = x.Id,
                name = x.Name

            }).ToList();

            ViewBag.company = new SelectList(collection, "id", "name", "--Select Company--");
            return Json(collection, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DisplayAccounts(int id = 0)
        {
            List<bool> sections = new List<bool>();
            //var accounts = CompanyAccountService.Where(c => c.CompanyId == 1032).ToList();
            var accounts = _vcompanyAccountService.Queryable().Where(c => c.CompanyId == id).OrderBy(o => o.GLAccountType).ToList();

            sections.Add(true);
            sections.Add(false);

            var leaseSections = new List<LeaseSection>();

            foreach (var isLease in sections)
            {
                var leaseSection = new LeaseSection();
                leaseSection.IsLease = isLease;
                if (isLease == true)
                    leaseSection.Name = String.Format("GL Accounts for Lease Components for {0}", accounts.FirstOrDefault().Companies);
                else
                {
                    leaseSection.Name = "GL Ledger Accounts for Variable Expenses & Non-Lease Payments";
                }
                leaseSection.LeaseTypes = getTypes(accounts, isLease);
                leaseSections.Add(leaseSection);
            }

            //return JsonConvert.SerializeObject(leaseSections);
            return Json(leaseSections, JsonRequestBehavior.AllowGet);
        }

        private List<LeaseType> getTypes(List<VCompanyAccount> accounts, bool isLease)
        {
            var leaseTypes = new List<LeaseType>();
            foreach (var type in GetLeaseTypes())
            {
                var leaseType = new LeaseType();

LeaseCrunch.Web/Views/Companies/Create.cshtml
@model LeaseCrunch.Entities.Company
@{
    ViewBag.Title = "Register";
}

    <div class="content">
        <div class="box-table">
            <div class="box-table-cell v-align-middle">
                <div class="container-fluid">
                    <div class="col-sm-offset-3 col-md-offset-4 col-sm-6 col-md-4">
                        <div class="form">
                            <h2>CREATE COMPANY</h2>
                            @using (Html.BeginForm())
                            {
                                @Html.AntiForgeryToken()
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "" })
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "" })
                                        @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.AccountingStandardId, "Accounting Standard", htmlAttributes: new { @class = "" })
                                        @Html.DropDownList("AccountingStandardId", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.AccountingStandardId, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.CountryId, "Country", htmlAttributes: new { @class = "" })
                                        @Html.DropDownList("CountryId", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "" })
                                        @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Address1, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Address2, htmlAttributes: new { @class = "" })
                                        @Html.EditorFor(model => model.Address2, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Address2, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "" })
                                        @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "" })
                                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.StateId, "State", htmlAttributes: new { @class = "" })
                                            @Html.DropDownList("StateId", null, htmlAttributes: new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "" })
                                        @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "" } })
                                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        <div class="row row-actions">
                                            <div class="col-sm-6">
                                                <button type="submit" class="btn btn-primary btn-block">CREATE COMPANY</button>
                                            </div>
                                            <div class="col-sm-4">
                                                <button type="submit" class="btn btn-secondary btn-block">CANCEL</button>
                                            </div>
                                        </div>
                                    </div>
                            }
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LeaseCrunch.Web/Views/Companies/Delete.cshtml
@model LeaseCrunch.Entities.Company
@{
    ViewBag.Title = "Register";
}



<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AccountingStandard.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountingStandard.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

LeaseCrunch.Web/Views/Companies/Details.cshtml
@model LeaseCrunch.Entities.Company

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.AccountingStandard.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AccountingStandard.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Country.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

LeaseCrunch.Web/Views/Companies/Edit.cshtml
@model LeaseCrunch.Entities.Company
@{
    ViewBag.Title = "Register";
}

<div class="content">
    <div class="box-table">
        <div class="box-table-cell v-align-middle">
            <div class="container-fluid">
                <div class="col-sm-offset-3 col-md-offset-4 col-sm-6 col-md-4">
                    <div class="form">
                        <h2>EDIT COMPANY</h2>
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "" })
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "" })
                                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.AccountingStandardId, "Accounting Standard", htmlAttributes: new { @class = "" })
                                @Html.DropDownList("AccountingStandardId", null, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.AccountingStandardId, "", new { @class = "text-danger" })
                            </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.CountryId, "Country", htmlAttributes: new { @class = "" })
                                    @Html.DropDownList("CountryId", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
                                </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Address1, htmlAttributes: new { @class = "" })
                                        @Html.EditorFor(model => model.Address1, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Address1, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Address2, htmlAttributes: new { @class = "" })
                                        @Html.EditorFor(model => model.Address2, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Address2, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "" })
                                        @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "" })
                                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.StateId, "State", htmlAttributes: new { @class = "" })
                                        @Html.DropDownList("StateId", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.StateId, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "" })
                                        @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "" } })
                                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                                    </div>

                                    <div class="form-group">
                                        <div class="row row-actions">
                                            <div class="col-sm-6">
                                                <button type="submit" class="btn btn-primary btn-block">UPDATE COMPANY</button>
                                            </div>
                                            <div class="col-sm-4">
                                                <button type="submit" class="btn btn-secondary btn-block">CANCEL</button>
                                            </div>
                                        </div>
                                    </div>
                        }
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

LeaseCrunch.Web/Views/Companies/_PoliciesPartial.cshtml
 <!-- Policies Tab Pane -->
<div role="tabpanel" class="tab-pane" id="policies">
    <div class="col-sm-12">
        <div class="row">
            <div class="col-sm-12">
                <div class="title">Customer Account Policies</div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" value="" id="EnableResellerAccesstomyAccount" name="EnableResellerAccesstomyAccount">
                        Enable Reseller Access to my Account
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" value="" id="RequireLeaseTermGuidanceWizardforeveryLease" name="RequireLeaseTermGuidanceWizardforeveryLease">
                        Require Lease Term Guidance Wizard for every Lease
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" value="" id="RequireClassificationWizardforeveryLease" name="RequireClassificationWizardforeveryLease">
                        Require Classification Wizard for every Lease
                    </label>
                </div>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<!-- /Policies Tab Pane -->
<script type="text/javascript">
    $(document).ready(function () {

        var baseUrl = "@Url.Action("PopulatePolicy", "Companies")";

        $(function () {
            var table = $.ajax({
                url: baseUrl,
                type: 'POST',
                data: {
                },
                success: function (response) {
                    $('#EnableResellerAccesstomyAccount').prop('checked', response.EnableResellerAccesstomyAccount);
                    $('#RequireLeaseTermGuidanceWizardforeveryLease').prop('checked', response.RequireLeaseTermGuidanceWizardforeveryLease);
                    $('#RequireClassificationWizardforeveryLease').prop('checked', response.RequireClassificationWizardforeveryLease);
                },
                complete: function () {
                    // alert('Complete: Do something.');
                },
                error: function (response) {
                    //alert(response.email);
                }
            });
        });

        $('body').on('click', 'input:checkbox', function () {
            //alert(this.id);
            UpdatePlolicy();
        });


        function UpdatePlolicy() {
            $.ajax({
                url: '@Url.Action("UpdatePolicy", "Companies")',
                type: 'POST',
                data: {
                    //customerid: $('#customerid').val(),
                    enablereselleraccesstomyaccount:  $('#EnableResellerAccesstomyAccount').is(':checked'),
                    requireleasetermguidancewizardforeverylease: $('#RequireLeaseTermGuidanceWizardforeveryLease').is(':checked'),
                    requireclassificationwizardforeverylease: $('#RequireClassificationWizardforeveryLease').is(':checked'),
                },
                success: function (response) {
                    table.ajax.reload();
                    // user configuration of all toastmessages to come:
                    //toastr.success($('#name').val() + ' updated successfully....!', 'SUCCESS', { timeOut: 3000, closeButton: true })
                    //$("#CompanyListing").modal('hide');
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    toastr.error(thrownError, 'ERROR', { timeOut: 3000, closeButton: true })
                }
            });
        }//End of UpdatePlolicy
    });
</script>