LeaseCrunch.Web/Models/AddLeaseInformation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using LeaseCrunch.Entities;

namespace LeaseCrunch.Web.Models
{

    public class LeaseViewModel
    {
        public LeaseViewModel()
        {
            leaseDocuments = new List<LeaseDocumentViewModel>();
        }
        public AddLeaseInformation AddLeaseInformation { get; set; }
        public List<LeaseDocumentViewModel> leaseDocuments { get; set; }
        public NonLeasePaymentsProvisionalViewModel nonLeasePayments { get; set; }
        public LeasePaymentsProvisionalViewModel leasePayments { get; set; }


    }
    public class AddLeaseInformation
    {
        //Id int
        //CompanyId   int

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Title")]
        public int? Id { get; set; }
        public string Title { get; set; }
        public int CompanyId { get; set; }
        public string Description { get; set; }
        public string Manufacturer { get; set; }
        public int AssetTypeId { get; set; }
        public double? Size { get; set; }
        public int CompanyLocationId { get; set; }
        public int LesserId { get; set; }
        public DateTime BeginDate { get; set; }
        public DateTime EndDate { get; set; }
        public int PaymentFrequencyId { get; set; }
        public int ROUAssetLife { get; set; }
        public int? Terms { get; set; }
        public string Comments { get; set; }
        public int CostCenterId { get; set; }
        public int ClassificationId { get; set; }
        public decimal DiscountRate { get; set; }
        public decimal IncentiveReceived { get; set; }
        public decimal InitialDirectCost { get; set; }
        public bool Status { get; set; }
    }


}

LeaseCrunch.Web/Controllers/LeasesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LeaseCrunch.Entities;
using LeaseCrunch.Service;
using LeaseCrunch.Common;
using Repository.Pattern.UnitOfWork;
using System.Web.Services;
using System.Web.Script.Services;
using System.Data.Entity.Validation;
using LeaseCrunch.Web.Models;
using Microsoft.AspNet.Identity;
using System.Text;
using System.Net.Mail;
using Microsoft.AspNet.Identity.EntityFramework;
using Newtonsoft.Json;
using LeaseCrunch.Web.NavigationAttribute;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Repository.Pattern.Infrastructure;
using System.IO;

namespace LeaseCrunch.Web.Controllers
{
    public class LeasesController : Controller
    {
        #region private variables
        private readonly IUnitOfWorkAsync _unitOfWorkAsync;
        private readonly ICompanyService _companiesService;
        private readonly ICountryService _countryService;
        private readonly IAccountingStandardService _accountingStandardService;
        private readonly ILeasesService _leasesService;
        private readonly ICustomizationLessorService _customizationLessorService;
        private readonly IStateService _stateService;
        private readonly ICustomizationAssetTypeService _customizationAssetTypesService;
        private readonly ILocationService _locationService;
        private readonly ILessersService _lessersService;
        private readonly ICustomizationCostCenterService _customizationCostCenterService;
        private readonly ICustomizationCustomFieldService _customizationCustomFieldService;
        private readonly ICustomizationCustomFieldsValuesService _customizationCustomFieldsValuesService;
        private readonly IClassificationService _classificationService;
        private readonly ICompanyAccountService _companyAccountService;
        private readonly INonLeasePaymentsProvisionalService _nonLeasePaymentService;
        private readonly ILeasePaymentsProvisionalService _leasePaymentService;
        private readonly ILeaseDocumentsService _leaseDocumentService;
        private readonly ILeaseGLService _leaseGLService;
        #endregion
        // GET: Leases

        #region variables intialization
        public LeasesController(IUnitOfWorkAsync unitOfWorkAsync, CompanyService companiesService, ICustomizationAssetTypeService customizationAssetTypesService, ILocationService locationService,
            ICustomizationCostCenterService customizationCostCenterService, ICustomizationCustomFieldService customizationCustomFieldService, CountryService countryService, StateService stateService,
            AccountingStandardService accountingStandardService, CustomizationLessorService customizationLessorService, LeasesService leasesService, LessersService lessersService, ICustomizationCustomFieldsValuesService customizationCustomFieldsValuesService,
            IClassificationService classificationService, ICompanyAccountService companyAccountService,
            INonLeasePaymentsProvisionalService nonLeasePayment, ILeasePaymentsProvisionalService leasePayment,
            ILeaseDocumentsService leaseDocument,
            ILeaseGLService leaseGl
            )
        {
            _customizationLessorService = customizationLessorService;
            _unitOfWorkAsync = unitOfWorkAsync;
            _companiesService = companiesService;
            _accountingStandardService = accountingStandardService;
            _stateService = stateService;
            _countryService = countryService;
            _locationService = locationService;
            _customizationCostCenterService = customizationCostCenterService;
            _customizationCustomFieldService = customizationCustomFieldService;
            _customizationAssetTypesService = customizationAssetTypesService;
            _leasesService = leasesService;
            _lessersService = lessersService;
            _customizationCustomFieldsValuesService = customizationCustomFieldsValuesService;
            _classificationService = classificationService;
            _companyAccountService = companyAccountService;
            _nonLeasePaymentService = nonLeasePayment;
            _leasePaymentService = leasePayment;
            _leaseDocumentService = leaseDocument;
            _leaseGLService = leaseGl;
        }
        #endregion

        #region CRUD Operations
        public ActionResult MyLeases()
        {
            return View();
        }

        [HttpGet]
        public ActionResult AddLeases()
        {
            LeaseViewModel model = new LeaseViewModel();
            AddLeaseInformation addLeaseInformation = new AddLeaseInformation();
            addLeaseInformation.BeginDate = DateTime.Now;
            addLeaseInformation.EndDate = DateTime.Now.AddYears(1);

            LeasePaymentClassifciationModels leasePaymentClassifciationModels = new LeasePaymentClassifciationModels();
            model.AddLeaseInformation = addLeaseInformation;
            model.leasePayments = new LeasePaymentsProvisionalViewModel();
            model.nonLeasePayments = new NonLeasePaymentsProvisionalViewModel();

            PopulateRecor();
            return View(model);
        }

        [HttpPost]
        [AllowAnonymous]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> AddLeases(AddLeaseInformation AddLeaseInformation)
        public ActionResult AddLeases(AddLeaseInformation AddLeaseInformation)
        {
            decimal id = 0;
            PopulateRecor();

            Lease Leases = new Lease();
            if (AddLeaseInformation.Id != null)
            {
                Leases = _leasesService.Find(AddLeaseInformation.Id);
            }
            Leases.CompanyId = AddLeaseInformation.CompanyId;
            Leases.Title = AddLeaseInformation.Title;
            Leases.Description = AddLeaseInformation.Description;
            Leases.Manufacturer = AddLeaseInformation.Manufacturer;
            Leases.AssetTypeId = AddLeaseInformation.AssetTypeId;
            Leases.Size = AddLeaseInformation.Size;
            Leases.CompanyLocationId = AddLeaseInformation.CompanyLocationId;
            Leases.LesserId = AddLeaseInformation.LesserId ;
            Leases.BeginDate = AddLeaseInformation.BeginDate;
            Leases.EndDate = AddLeaseInformation.EndDate;
            Leases.ROUAssetLife = AddLeaseInformation.ROUAssetLife;
            Leases.Terms = AddLeaseInformation.Terms;
            Leases.Comments = AddLeaseInformation.Comments;
            Leases.CostCenterId = AddLeaseInformation.CostCenterId;


            Leases.PaymentFrequencyId = 1;
            Leases.ClassificationId = 1;
            Leases.DiscountRate = 0;
            Leases.IncentiveReceived = 0;
            Leases.InitialDirectCost = 0;
            Leases.Status = true;
            IList<CustomizationCustomField> customizationCustomFields = new List<CustomizationCustomField>();
            int CustomerId = Convert.ToInt32(@Session["customerid"].ToString());
            customizationCustomFields = _customizationCustomFieldService.Queryable().Where(x => x.CustomerId == CustomerId).ToList();
            foreach(var customizationCustomField in customizationCustomFields)
            {
                string ids = "custom_" + customizationCustomField.Id;
                if (!string.IsNullOrEmpty(Request.Form[ids]))
                {
                    CustomizationCustomFieldsValue customizationCustomFieldsValue = new CustomizationCustomFieldsValue();
                    customizationCustomFieldsValue.Lease = Leases;
                    customizationCustomFieldsValue.CustomizationCustomFieldsId = customizationCustomField.Id;
                    customizationCustomFieldsValue.value = Request.Form[ids].ToString();
                    Leases.CustomizationCustomFieldsValues.Add(customizationCustomFieldsValue);
                    _customizationCustomFieldsValuesService.Insert(customizationCustomFieldsValue);
                }
            }
            if (AddLeaseInformation.Id == null)
                _leasesService.Insert(Leases);
            else
            {
                Leases.ObjectState = ObjectState.Modified;
                _leasesService.Update(Leases);
            }
            try
            {
               _unitOfWorkAsync.SaveChanges();
                id = Leases.Id;
            }
            catch (DbEntityValidationException e)
            {
                string error = string.Empty;
                foreach (var eve in e.EntityValidationErrors)
                {
                    error = string.Format("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        error += string.Format("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                string r = error;
                //throw;

                ModelState.Remove("Id");

            }

            TempData["LeaseId"] = id;
            //return View(AddLeaseInformation);
            return Json(new { Status = "0", Message = "Lease Added Sucessfully!", Id = id }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult AddLeaseGL(LeaseGLAccountsViewModel model)
        {
            try
            {
                decimal leaseid =Convert.ToDecimal(Request.Form["GLAccountsLeaseId"]);
                LeaseGLAccount accountModel = new LeaseGLAccount();
                accountModel.AmortExpense = model.AmortExpense;
                accountModel.CashAP = model.CashAP;
                accountModel.GLDescription = model.GLDescription;

LeaseCrunch.Web/Views/Leases/AddLeases.cshtml
@using LeaseCrunch.Web.Models

@model LeaseViewModel

@{
    ViewBag.Title = "Add Lease - LeaseCrunch";
}
<style>
    .tab {
        display: none;
    }
</style>

@Html.Partial("_CreateOrUpdate", @Model)

<script>
    //jQuery.validator.setDefaults({
    //    debug: true,
    //    success: "valid"
    //});
</script>
  
    @Scripts.Render("~/content/datepicker/js", "~/content/steps/js", "~/bundles/datatable", "~/content/validator/js", "~/content/grid/js")
    @Styles.Render("~/content/validator/css"),

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script> 

LeaseCrunch.Web/Views/Leases/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

LeaseCrunch.Web/Views/Leases/_AddLeaseDocuments.cshtml
@using LeaseCrunch.Web.Models
@model IEnumerable<LeaseCrunch.Web.Models.LeaseDocumentViewModel>
<!-- Documents Title Row -->
<div class="row">
    <div class="col-sm-4">
        <div class="title">Documents</div>
    </div>
    <div class="col-sm-offset-6 col-sm-2">
        <button class="btn btn-primary btn-block" id="btnUpload">Upload</button>
    </div>
    <div class="col-xs-12 visible-xs"><div class="top-buffer-20"></div></div>
</div>
<!-- /Documents Title Row -->
<!-- Documents Title Row -->
<div class="row">
    <div class="col-sm-12 data-table-with-out-dataTables_info_and_paginate">
        <table id="LeaseDocumentsTable" class="table table-bordered table-listing js-data-table">
            <thead>
                <tr>
                    <th>Document Name</th>
                    <th class="text-center">Date Uploaded</th>
                    <th class="text-center">Size</th>
                </tr>
            </thead>
            <tbody id="searchResult"></tbody>
            @*<tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.UploadDate</td>
                        <td>@item.Size</td>
                        <td class="text-center"><a href=""><i class="fa fa-trash icon-delete"></i></a></td>
                    </tr>
                }
               
            </tbody>*@
        </table>
    </div>
    <div class="row">
        <div class="col-sm-2">
            <button type="button" id="btnPrevLeaseDoc" class="btn btn-block btn-primary">Prev</button>
        </div>
    </div>
</div>
<div id="test"></div>
<!-- /Documents Title Row -->

<!-- Modal Company Listing -->
<div class="modal fade" id="UploadModel" tabindex="-1" role="dialog" aria-labelledby="AddLessorLabel">
    
@*@using (Ajax.BeginForm("UploadFiles", "Leases", new AjaxOptions { HttpMethod = "POST", OnComplete = "Complete", OnSuccess = "Success" }))*@
   @*@using (Html.BeginForm("", "", FormMethod.Post, new {@id="myform",enctype = "multipart/form-data" }))
   {
    @Html.AntiForgeryToken()*@
   
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="AddLessorLabel">Lease Documents</h4>
                </div>
                <div class="modal-body">
                    <form id="myform">
                        <div class="form-horizontal">
                            <input type="hidden" name="DocumentLeaseId" id="DocumentLeaseId">
                            <div class="form-group">
                                <label for="" class="col-sm-4 control-label">Select Document</label>
                                <div class="col-sm-7">
                                    <input id="fileInput" type="file" multiple><br>
                                    <div class="required-staric">*</div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-4 col-sm-2">
                                    <input type="submit" class="btn btn-block btn-primary" value="Upload file" />
                                </div>
                                <div class="col-sm-2">
                                    <button class="btn btn-block btn-secondary" data-dismiss="modal">CANCEL</button>
                                </div>
                            </div>
                        </div>
                    </form>
                        <div class="clearfix"></div>
</div>

            </div>
        </div>
    
        @*}*@
</div>

@*<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>*@
<script>

    $("#btnPrevLeaseDoc").click(function () {
        $("#LeaseDocumentsDiv").hide();
        $("#NonLeasePaymentsDiv").show();
        $("#LeaseDocStep").removeClass("active")
        $("#NonLeasePaymentStep").addClass("active")
        $("#progressDiv").css("width", '60%');
    });

    //Show modal for upload documents
    $('body').on('click', '#btnUpload', function () {
        $("#UploadModel").modal('show');
    });

    //uploading documents submit
    (function () {

        var bar = $('.progress-bar');
        var percent = $('.progress-bar');
        var status = $('#status');

        //$('#myform').ajaxForm({
        //    beforeSend: function () {
        //        status.empty();
        //        var percentVal = '0%';
        //        bar.width(percentVal)
        //        percent.html(percentVal);
        //    },
        //    uploadProgress: function (event, position, total, percentComplete) {
        //        var percentVal = percentComplete + '%';
        //        bar.width(percentVal)
        //        percent.html(percentVal);
        //    },
        //    success: function () {
        //        alert("success")
        //        var percentVal = '100%';
        //        bar.width(percentVal)
        //        percent.html(percentVal);
        //    },
        //    complete: function (xhr) {
        //        alert("complete")
        //        status.html(xhr.responseText);
        //    }
        //});

    })();


    function changeDate(input)
    {
        var dtStart = new Date(parseInt(input.substr(6)));
        var dtStartWrapper = moment(dtStart);
        return dtStartWrapper.format('DD/MM/YYYY')
    }

    document.getElementById('myform').onsubmit = function () {
        var formdata = new FormData(); //FormData object
        var fileInput = document.getElementById('fileInput');
        //Iterating through each files selected in fileInput
        for (i = 0; i < fileInput.files.length; i++) {
            //Appending each file to FormData object
            formdata.append(fileInput.files[i].name, fileInput.files[i]);
        }
        var leaseid = document.getElementById('DocumentLeaseId');
        formdata.append(leaseid.name,leaseid.value)
        //Creating an XMLHttpRequest and sending
        var xhr = new XMLHttpRequest();
        xhr.open('POST', '/Leases/Upload');
        xhr.send(formdata);
        xhr.onreadystatechange = function () {
            if (xhr.readyState == 4 && xhr.status == 200) {
                var output = $("#searchResult");
                output.empty();
                var obj = jQuery.parseJSON(xhr.responseText);
                for (var i = 0; i < obj.length ; i++) {
                    var document = obj[i];
                    output.append("<tr><td>" + document.Name + "</td><td>" +
                 changeDate(document.UploadDate) + "</td><td>" + (document.Size/1024) + "MB</td></tr>");
                }
                $('#UploadModel').modal('hide');
                $("#progressDiv").css("width", '100%');
                toastr.success('Lease documents uploaded successfully....!', 'SUCCESS', { timeOut: 3000, closeButton: true });
            }
        }
        return false;
    }


</script>

LeaseCrunch.Web/Views/Leases/_AddLeaseGLAccount.cshtml
   <!-- GL Account Form Row -->
@using (Ajax.BeginForm("AddLeaseGL", "Leases", new AjaxOptions { HttpMethod = "POST", OnComplete = "CompletePaymentClassification", OnSuccess = "LeaseGLSucess", OnFailure = "LeaseGLFailure" }))
{
    <input type="hidden" name="GLAccountsLeaseId" id="GLAccountsLeaseId" />
<div class="row">
    <div class="container-fluid">
        <div class="col-xs-12 box bg-white shadow">
            <!-- /Lease Payment and Classification Form Row -->

            <div class="row">
                <div class="col-sm-12">
                    <div class="title">
                       GL Account
                        <div><em>Note: Customer GL Descriptions and GL Numbers can be added or edited in <a href="">Settings</a>:</em></div>
                    </div>
                </div>
                <div class="col-xs-12 visible-sm visible-xs">
                    <div class="top-buffer-20"></div>
                </div>
            </div>
           
            
            <div class="form-horizontal" id="GLAccountsDiv">
              
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                <button type="button" id="btnPrevLeaseGL" class="btn btn-block btn-primary">Prev</button>
            </div>
            <div class="col-sm-2 pull-right">
                <button type="submit" class="btn btn-block btn-primary">Save & Next</button>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
}
<!-- /GL Account Form Row -->


<script>

    $("#Classification").change(function () {
        var model = {
            CompanyId: 2075,
            GLAccountType: $("#Classification").val()
        }
        $.ajax({
            cache: false,
            type: "GET",
            url: "/Leases/GetGlAccounts",
            data: model,
            success: function (data) {
                $("#GLAccountsDiv").html(data);
            },
            error: function (xhr, ajaxOptions, thrownError) {
                //alert('Failed to retrieve books.');
            }
        });
    });

    $(document).ready(function ()
    {
        var model = {
            CompanyId: 2075,
            GLAccountType:1
        }
            $.ajax({
                cache: false,
                type: "GET",
                url: "/Leases/GetGlAccounts",
                data: model,
            success: function (data)
            {
                $("#GLAccountsDiv").html(data);
            },
            error: function (xhr, ajaxOptions, thrownError)
            {
                //alert('Failed to retrieve books.');
            }
        });
    });

    $("#btnPrevLeaseGL").click(function () {
        $("#LeaseGLAccountsDiv").hide();
        $("#LeasePaymentsDiv").show();
        $("#LeaseGLAccounts").removeClass("active")
        $("#LeasePaymentStep").addClass("active")
        $("#progressDiv").css("width", '20%');
    });

    function LeaseGLSucess(data) {
        toastr.success('GL Accounts added successfully.', 'SUCCESS', { timeOut: 3000, closeButton: true });
        //hiding leaseinfo div and moving to laesepayments
        setTimeout(function (d) {
            $("#LeaseGLAccountsDiv").hide();
            $("#NonLeasePaymentsDiv").show();
            $("#LeaseGLAccounts").removeClass("active")
            $("#NonLeasePaymentStep").addClass("active")
            $("#progressDiv").css("width", '60%');
        }, 2000);
    }

    function LeaseGLFailure() {
        toastr.error("Some error occured", 'ERROR', { timeOut: 3000, closeButton: true });
    }
</script>

LeaseCrunch.Web/Views/Leases/_CreateOrUpdate.cshtml
@using LeaseCrunch.Web.Models
@model LeaseViewModel
<!-- Content -->
<div class="content">
    <div class="col-sm-12">
        <div class="row">
            <div class="row-add-lease-title row-table bg-white shadow">
                <div class="col-sm-6 left">
                    <div class="title">Add Lease Information</div>
                </div>
                <div class="col-sm-6 right">
                    <div class="title">
                        <span>Lease ID: CUS-2112</span>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div class="top-buffer-20"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-offset-1 col-sm-offset-0 col-sm-12 col-md-10">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="box bg-white shadow">
                            <div class="col-xs-12">
                                <div class="row">
                                    <div class="col-xs-12">
                                        <div class="step-indicator">
                                            <a  id="LeaseInfoStep" class="active"><span class="number">1</span> Step 1</a>
                                            <a  id="LeasePaymentStep"><span class="number">2</span> Step 2</a>
                                            <a id="LeaseGLAccounts"><span class="number">3</span> Step 3</a>
                                            <a  id="NonLeasePaymentStep"><span class="number">4</span> Step 4</a>
                                            <a  id="LeaseDocStep"><span class="number">5</span> Step 5</a>
                                            <a >@*<span class="number">5</span> Step 5*@</a>
                                            <div class="progress">
                                                <div id="progressDiv" class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                                    <span class="sr-only">20% Complete</span>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="row" id="LeaseInfoDiv">
                                    <div class="col-xs-12">
                                        @Html.Partial("_AddLeaseInformation", Model.AddLeaseInformation)
                                    </div>
                                </div>
                                <div class="row" id="LeasePaymentsDiv">
                                    <div class="col-xs-12">
                                        @Html.Partial("_AddLeasePayments", Model.leasePayments)
                                    </div>
                                </div>
                                <div class="row" id="NonLeasePaymentsDiv">
                                    <div class="col-xs-12">
                                        @Html.Partial("_AddNonLeasePayments", Model.nonLeasePayments)
                                    </div>
                                </div>
                                <div class="row" id="LeaseDocumentsDiv">
                                    <div class="col-xs-12">
                                      @Html.Partial("_AddLeaseDocuments", Model.leaseDocuments)
                                    </div>
                                </div>
                                <div class="row" id="LeaseGLAccountsDiv">
                                    <div class="col-xs-12">
                                        @Html.Partial("_AddLeaseGLAccount")
                                    </div>
                                </div>
                                <div class="clearfix"></div>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<!-- /Content -->

LeaseCrunch.Web/Views/Leases/_FinanceGLAccounts.cshtml
<div class="title">
    Finance Lease Accounts
</div>
<div class="form-group">
    <label class="control-label col-sm-5"><div class="box-table"><div class="box-table-cell v-align-middle">Cash / AP</div></div></label>
    <div class="col-sm-4">
        @Html.DropDownList("CashAccountPayble", null, htmlAttributes: new { id = "CashAccountPayble", @class = "form-control" })
</div>
</div>
<div class="form-group">
    <label class="control-label col-sm-5"><div class="box-table"><div class="box-table-cell v-align-middle">ROU Asset</div></div></label>
    <div class="col-sm-4">
        @Html.DropDownList("RouAsset", null, htmlAttributes: new { id = "RouAsset", @class = "form-control" })
    </div>
</div>
<div class="form-group">
    <label class="control-label col-sm-5"><div class="box-table"><div class="box-table-cell v-align-middle">LT Lease Liability</div></div></label>
    <div class="col-sm-4">
        @Html.DropDownList("LTLeaseLiab", null, htmlAttributes: new { id = "LTLeaseLiab", @class = "form-control" })
    </div>
</div>
<div class="form-group">
    <label class="control-label col-sm-5"><div class="box-table"><div class="box-table-cell v-align-middle">ST Lease Liability</div></div></label>
    <div class="col-sm-4">
        @Html.DropDownList("STLeaseLiab", null, htmlAttributes: new { id = "STLeaseLiab", @class = "form-control" })
    </div>
</div>
<div class="form-group">
    <label class="control-label col-sm-5"><div class="box-table"><div class="box-table-cell v-align-middle">Amortization Expense</div></div></label>
    <div class="col-sm-4">
        @Html.DropDownList("AmortizationExp", null, htmlAttributes: new { id = "AmortizationExp", @class = "form-control" })
    </div>
</div>
<div class="form-group">
    <label class="control-label col-sm-5"><div class="box-table"><div class="box-table-cell v-align-middle">Interest Expense</div></div></label>
    <div class="col-sm-4">
        @Html.DropDownList("InterestExp", null, htmlAttributes: new { id = "InterestExp", @class = "form-control" })
    </div>
</div>

LeaseCrunch.Web/Views/Leases/_OperatingGLAccounts.cshtml
<div class="title">
    Operating Lease Accounts
</div>
<div class="form-group">
    <label class="control-label col-sm-5"><div class="box-table"><div class="box-table-cell v-align-middle">Cash / AP</div></div></label>
    <div class="col-sm-4">
        @Html.DropDownList("CashAccountPayble", null, htmlAttributes: new { id = "CashAccountPayble", @class = "form-control" })
     </div>
</div>
<div class="form-group">
    <label class="control-label col-sm-5"><div class="box-table"><div class="box-table-cell v-align-middle">ROU Asset</div></div></label>
    <div class="col-sm-4">
        @Html.DropDownList("RouAsset", null, htmlAttributes: new { id = "RouAsset", @class = "form-control" })
    </div>
</div>
<div class="form-group">
    <label class="control-label col-sm-5"><div class="box-table"><div class="box-table-cell v-align-middle">LT Lease Liability</div></div></label>
    <div class="col-sm-4">
        @Html.DropDownList("LTLeaseLiab", null, htmlAttributes: new { id = "LTLeaseLiab", @class = "form-control" })
    </div>
</div>
<div class="form-group">
    <label class="control-label col-sm-5"><div class="box-table"><div class="box-table-cell v-align-middle">ST Lease Liability</div></div></label>
    <div class="col-sm-4">
        @Html.DropDownList("STLeaseLiab", null, htmlAttributes: new { id = "STLeaseLiab", @class = "form-control" })
    </div>
</div>
<div class="form-group">
    <label class="control-label col-sm-5"><div class="box-table"><div class="box-table-cell v-align-middle">Rent Expense</div></div></label>
    <div class="col-sm-4">
        @Html.DropDownList("RentExp", null, htmlAttributes: new { id = "RentExp", @class = "form-control" })
    </div>
</div>